name: frontier-deu

channels:
  - conda-forge
  - defaults
  
dependencies:
  - black
  - branca
  - flake8
  - isort
  - pip
  - ipykernel==6.29.5
  - pandas==2.2.2 
  - python==3.10
  - seaborn==0.13.2
  - openpyxl==3.1.4
  - odfpy==1.4.1
  - jupyter==1.0.0
  - folium==0.17.0
  - scikit-learn==1.5.1
  - numpy==2.0.0